// Package vvn provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package vvn

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
)

const (
	Api_keyScopes = "api_key.Scopes"
)

// Defines values for OCRResultDocument.
const (
	ARMYID           OCRResultDocument = "ARMY ID"
	CCCD             OCRResultDocument = "CCCD"
	CHIPID           OCRResultDocument = "CHIP ID"
	DRIVERLICENSEOLD OCRResultDocument = "DRIVER LICENSE OLD"
	DRIVERLICENSEPET OCRResultDocument = "DRIVER LICENSE PET"
	NEWID            OCRResultDocument = "NEW ID"
	OLDID            OCRResultDocument = "OLD ID"
	PASSPORT         OCRResultDocument = "PASSPORT"
	POLICEID         OCRResultDocument = "POLICE ID"
)

// OCRResult defines model for OCRResult.
type OCRResult struct {
	// Thông tin mô tả các loại giấy tờ
	Document *OCRResultDocument `json:"document,omitempty"`
	Id       *string            `json:"id,omitempty"`
	Name     *string            `json:"name,omitempty"`
}

// Thông tin mô tả các loại giấy tờ
type OCRResultDocument string

// Ocr defines model for Ocr.
type Ocr struct {
	// Chú ý: Với cùng 1 loại giấy tờ có 2 mặt (ví dụ: Căn cước Giá trị ngưỡng để kiểm tra id_full về mặt đầy đủ thông tin công dân, CMN
	IDFullThr *float32 `json:"id_full_thr,omitempty"`
	Image     string   `json:"image"`
	RequestID string   `json:"request_id"`
}

// NewOcrRecognitionJSONRequestBody defines body for NewOcrRecognition for application/json ContentType.
type NewOcrRecognitionJSONRequestBody = Ocr

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// NewOcrRecognition request with any body
	NewOcrRecognitionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	NewOcrRecognition(ctx context.Context, body NewOcrRecognitionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) NewOcrRecognitionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewOcrRecognitionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NewOcrRecognition(ctx context.Context, body NewOcrRecognitionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewOcrRecognitionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewNewOcrRecognitionRequest calls the generic NewOcrRecognition builder with application/json body
func NewNewOcrRecognitionRequest(server string, body NewOcrRecognitionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNewOcrRecognitionRequestWithBody(server, "application/json", bodyReader)
}

// NewNewOcrRecognitionRequestWithBody generates requests for NewOcrRecognition with any type of body
func NewNewOcrRecognitionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ocr/recognition")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// NewOcrRecognition request with any body
	NewOcrRecognitionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewOcrRecognitionResponse, error)

	NewOcrRecognitionWithResponse(ctx context.Context, body NewOcrRecognitionJSONRequestBody, reqEditors ...RequestEditorFn) (*NewOcrRecognitionResponse, error)
}

type NewOcrRecognitionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OCRResult
}

// Status returns HTTPResponse.Status
func (r NewOcrRecognitionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NewOcrRecognitionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// NewOcrRecognitionWithBodyWithResponse request with arbitrary body returning *NewOcrRecognitionResponse
func (c *ClientWithResponses) NewOcrRecognitionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewOcrRecognitionResponse, error) {
	rsp, err := c.NewOcrRecognitionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewOcrRecognitionResponse(rsp)
}

func (c *ClientWithResponses) NewOcrRecognitionWithResponse(ctx context.Context, body NewOcrRecognitionJSONRequestBody, reqEditors ...RequestEditorFn) (*NewOcrRecognitionResponse, error) {
	rsp, err := c.NewOcrRecognition(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewOcrRecognitionResponse(rsp)
}

// ParseNewOcrRecognitionResponse parses an HTTP response from a NewOcrRecognitionWithResponse call
func ParseNewOcrRecognitionResponse(rsp *http.Response) (*NewOcrRecognitionResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NewOcrRecognitionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OCRResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
