// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
)

func (s *Server) notFound(w http.ResponseWriter, r *http.Request) {
	s.cfg.NotFound(w, r)
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	if len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	// Static code generated router with unwrapped path search.
	switch r.Method {
	case "POST":
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v3.2/"
			if l := len("/v3.2/"); len(elem) >= l && elem[0:l] == "/v3.2/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'f': // Prefix: "faceid/verification"
				if l := len("faceid/verification"); len(elem) >= l && elem[0:l] == "faceid/verification" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf: NewFaceIDVerification
					s.handleNewFaceIDVerificationRequest([0]string{}, w, r)

					return
				}
			case 'o': // Prefix: "ocr/recognition"
				if l := len("ocr/recognition"); len(elem) >= l && elem[0:l] == "ocr/recognition" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf: NewOCRRecognition
					s.handleNewOCRRecognitionRequest([0]string{}, w, r)

					return
				}
			}
		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name  string
	count int
	args  [0]string
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.name
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
func (s *Server) FindRoute(method, path string) (r Route, _ bool) {
	var (
		args = [0]string{}
		elem = path
	)
	r.args = args
	if elem == "" {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch method {
	case "POST":
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v3.2/"
			if l := len("/v3.2/"); len(elem) >= l && elem[0:l] == "/v3.2/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'f': // Prefix: "faceid/verification"
				if l := len("faceid/verification"); len(elem) >= l && elem[0:l] == "faceid/verification" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf: NewFaceIDVerification
					r.name = "NewFaceIDVerification"
					r.args = args
					r.count = 0
					return r, true
				}
			case 'o': // Prefix: "ocr/recognition"
				if l := len("ocr/recognition"); len(elem) >= l && elem[0:l] == "ocr/recognition" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf: NewOCRRecognition
					r.name = "NewOCRRecognition"
					r.args = args
					r.count = 0
					return r, true
				}
			}
		}
	}
	return r, false
}
