// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

var _ Handler = UnimplementedHandler{}

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

// NewFaceIDVerification implements newFaceIDVerification operation.
//
// POST /faceid/verification
func (UnimplementedHandler) NewFaceIDVerification(ctx context.Context, req VerificationInput) (r NewFaceIDVerificationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewOCRRecognition implements newOCRRecognition operation.
//
// Cung cấp phương thức để trích xuất thông tin trên các văn bản tài liệu như:
// Giấy phép lái xe (GPLX), Passport, CMND, Căn cước công dân (CCCD) ...
//
// POST /ocr/recognition
func (UnimplementedHandler) NewOCRRecognition(ctx context.Context, req OCRInputForm) (r NewOCRRecognitionRes, _ error) {
	return r, ht.ErrNotImplemented
}
