// Code generated by ogen, DO NOT EDIT.
package api

type FaceRecognitionReq interface {
	faceRecognitionReq()
}

type FaceRecognitionRes interface {
	faceRecognitionRes()
}

type FaceRegisterReq interface {
	faceRegisterReq()
}

type FaceRegisterRes interface {
	faceRegisterRes()
}

type FaceUnregisterRes interface {
	faceUnregisterRes()
}

type FaceVerificationReq interface {
	faceVerificationReq()
}

type FaceVerificationRes interface {
	faceVerificationRes()
}

type OCRecognitionRes interface {
	oCRecognitionRes()
}
